### ISSUE TITLE
auth-password is not enabled.

### ISSUE THREAD

**Issue by ReichKV** [DamienCassou/auth-password-store#31]
Hi,
I am trying to use your  program. I put  the following in my init file, and start emacs as a daemon:

(use-package auth-password-store
  :ensure t
  :config
  (auth-pass-enable)
  )

However, auth pass is not initialize at startup.  I need to manually execute (auth-pass-enable), then the program works as it should.

Could you help me to initialize the auth-pass at start?

**Comment by DamienCassou** [comment]
Indeed, that's a use-package usage problem. When you use `:config`, you tell use-package to only execute the code after the package is loaded: as a result, if you never load the package, the code is never executed. You have two options here: either you force the package to load at startup (with `:demand t`) or you tell use-package to execute the function `auth-pass-enable` before loading auth-password-store (with `:init` instead of `:config`). The second approach works because `auth-pass-enable` is an autoload: if you try to execute the function before it is defined, the package will first be loaded and then the function executed.

For your information, I have this in my [.emacs.d](https://github.com/DamienCassou/emacs.d):

```emacs
(use-package auth-password-store
  :after auth-source
  :init
  (progn
    (setq auth-sources '(password-store))))
```

I don't use `auth-pass-enable` because this function adds password-store to the list of authentication sources whereas what I want is to only use password-store. But you can replace that with `(auth-pass-enable)` without problem.

I'm closing the issue now. Please re-open if your problem is not solved.

**Comment by ReichKV** [comment]
Sorry, I still cannot initialize the package. I tried:
(use-package auth-source
  :init
  (progn
    (setq auth-source-debug t)
    (setq auth-source-do-cache nil)))

(use-package auth-password-store
  :after auth-source
  :init
  (progn
    (setq auth-sources '(password-store))))

from your config and also:

``(use-package auth-password-store
   :ensure t
   :init
   (auth-pass-enable)
   )
``
 and 

``(use-package auth-password-store
  :demand t
  :config
  (auth-pass-enable)
  )
``
Nothing works
