### ISSUE TITLE
MELPA isn't getting updated

### ISSUE THREAD

**Issue by jabranham** [DamienCassou/auth-password-store#62]
Any idea why auth-password-store in MELPA isn't getting updated? I just updated `helm-pass.el` to use the renamed `auth-source-pass` stuff and now the CI is failing.

**Comment by danielsz** [comment]
Same problem here.

**Comment by jabranham** [comment]
I'm just guessing but I bet it's because none of the recent commits were authored after Feb 14th, even though they were committed more recently. 

The only two that were (the two most recent) are empty or just touch the README, which probably doesn't trigger a rebuild by MELPA.

Pushing a commit that changes... something? (whitespace?) on the `.el` file I bet will fix it.

**Comment by orther** [comment]
Just checked and it looks like MELPA is updated after v4.0.0 was pushed 2 days ago.

**Comment by DamienCassou** [comment]
Sorry guys I haven't seen your message before. I was actually unsubscribed from this project :-(. MELPA didn't try to build the project because I forgot to rename it there. I have done that last week. Everything should be back to normal.

Thanks @orther and @jabranham for taking care of the project for me :-).
