### ISSUE TITLE
Multiple hosts support

### ISSUE THREAD

**Issue by iquiw** [DamienCassou/auth-password-store#90]
When using `auth-source-pass` with Gnus, it always raises warning `auth-source-pass ignores all but first host in spec`.

I wonder if there is any difficulty to support multiple hosts in `auth-source-pass-search`.

**Comment by DamienCassou** [comment]
> I wonder if there is any difficulty to support multiple hosts in `auth-source-pass-search`.

@kamidon and me are currently refactoring the project. I hope this feature can be implemented easily once this is done.

**Comment by DamienCassou** [comment]
@iquiw : the master branch now contains the new code. Would you mind having a look at implementing what you need?

**Comment by iquiw** [comment]
@DamienCassou Great! I will take a look.

**Comment by dbausch** [comment]
I am currently debugging this, too. It's not "multiple hosts" which are in the <code>host</code> argument. It's a pair consisting of the Gnus server name and the actual host address. I have multiple accounts at the same provider. In Gnus I use different short identifiers as the server name to distinguish them. This works with .authinfo.gpg as I can use that short identifier as the machine name there. To support this situation we need something equivalent. I just checked that it is indeed possible to add, for example, an nnimap-user key to the server definition. This is properly supplied to the search function in the <code>user</code> argument. I think <code>auth-source-pass-search</code> could use the <code>cdr</code> of the pair supplied in host instead of the first non-nil list entry (in my situation). This would allow me to continue using the short identifier to distinguish multiple accounts at the same provider.

**Comment by DamienCassou** [comment]
if one of you make a PR, please make sure to add at least a unit-test.

**Comment by dbausch** [comment]
I am not sure what other applications are using auth-source and what the API contract of the search function is in general. I am on a vacation the next days and not very proficient in elisp.  But I'll do my best when I'm back.

**Comment by iquiw** [comment]
According to the docstring of `auth-source-search`, it is single host or list of them. (I am not sure symbol is actually supported, for example, by `auth-source-netrc`)

> A string value is always matched literally.  A symbol is matched
as its string value, literally.  All the SPEC values can be
single values (symbol or string) or lists thereof (in which case
any of the search terms matches).

(As in above, `port` or `user` could be a list too, though it is not scope of this issue)

@dbausch If you are willing to take this up, I will wait for it.
